/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedEditProfileRouteImport } from './routes/_authenticated/edit-profile'
import { Route as AuthenticatedFollowRequestsRouteImport } from './routes/_authenticated/follow-requests'
import { Route as AuthenticatedFollowUsersRouteImport } from './routes/_authenticated/follow-users'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as GuestSigninRouteImport } from './routes/_guest/signin'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as AuthenticatedPostsPostIdRouteImport } from './routes/_authenticated/posts.$postId'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users.$userId'
import { Route as AuthenticatedPostsPostIdLikesRouteImport } from './routes/_authenticated/posts.$postId_.likes'
import { Route as AuthenticatedUsersUserIdIndexRouteImport } from './routes/_authenticated/users.$userId/index'
import { Route as AuthenticatedUsersUserIdCommentsRouteImport } from './routes/_authenticated/users.$userId/comments'
import { Route as AuthenticatedUsersUserIdLikesRouteImport } from './routes/_authenticated/users.$userId/likes'
import { Route as AuthenticatedUsersUserIdFollowersRouteImport } from './routes/_authenticated/users.$userId_.followers'
import { Route as AuthenticatedUsersUserIdFollowingsRouteImport } from './routes/_authenticated/users.$userId_.followings'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditProfileRoute =
  AuthenticatedEditProfileRouteImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFollowRequestsRoute =
  AuthenticatedFollowRequestsRouteImport.update({
    id: '/follow-requests',
    path: '/follow-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFollowUsersRoute =
  AuthenticatedFollowUsersRouteImport.update({
    id: '/follow-users',
    path: '/follow-users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const GuestSigninRoute = GuestSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedPostsPostIdRoute =
  AuthenticatedPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPostsPostIdLikesRoute =
  AuthenticatedPostsPostIdLikesRouteImport.update({
    id: '/posts/$postId_/likes',
    path: '/posts/$postId/likes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdIndexRoute =
  AuthenticatedUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUsersUserIdRoute,
  } as any)
const AuthenticatedUsersUserIdCommentsRoute =
  AuthenticatedUsersUserIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedUsersUserIdRoute,
  } as any)
const AuthenticatedUsersUserIdLikesRoute =
  AuthenticatedUsersUserIdLikesRouteImport.update({
    id: '/likes',
    path: '/likes',
    getParentRoute: () => AuthenticatedUsersUserIdRoute,
  } as any)
const AuthenticatedUsersUserIdFollowersRoute =
  AuthenticatedUsersUserIdFollowersRouteImport.update({
    id: '/users/$userId_/followers',
    path: '/users/$userId/followers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdFollowingsRoute =
  AuthenticatedUsersUserIdFollowingsRouteImport.update({
    id: '/users/$userId_/followings',
    path: '/users/$userId/followings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AuthenticatedAboutRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/follow-requests': typeof AuthenticatedFollowRequestsRoute
  '/follow-users': typeof AuthenticatedFollowUsersRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signin': typeof GuestSigninRoute
  '/signup': typeof GuestSignupRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRouteWithChildren
  '/posts/$postId/likes': typeof AuthenticatedPostsPostIdLikesRoute
  '/users/$userId/comments': typeof AuthenticatedUsersUserIdCommentsRoute
  '/users/$userId/likes': typeof AuthenticatedUsersUserIdLikesRoute
  '/users/$userId/followers': typeof AuthenticatedUsersUserIdFollowersRoute
  '/users/$userId/followings': typeof AuthenticatedUsersUserIdFollowingsRoute
  '/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AuthenticatedAboutRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/follow-requests': typeof AuthenticatedFollowRequestsRoute
  '/follow-users': typeof AuthenticatedFollowUsersRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signin': typeof GuestSigninRoute
  '/signup': typeof GuestSignupRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/posts/$postId/likes': typeof AuthenticatedPostsPostIdLikesRoute
  '/users/$userId/comments': typeof AuthenticatedUsersUserIdCommentsRoute
  '/users/$userId/likes': typeof AuthenticatedUsersUserIdLikesRoute
  '/users/$userId/followers': typeof AuthenticatedUsersUserIdFollowersRoute
  '/users/$userId/followings': typeof AuthenticatedUsersUserIdFollowingsRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/edit-profile': typeof AuthenticatedEditProfileRoute
  '/_authenticated/follow-requests': typeof AuthenticatedFollowRequestsRoute
  '/_authenticated/follow-users': typeof AuthenticatedFollowUsersRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_guest/signin': typeof GuestSigninRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRouteWithChildren
  '/_authenticated/posts/$postId_/likes': typeof AuthenticatedPostsPostIdLikesRoute
  '/_authenticated/users/$userId/comments': typeof AuthenticatedUsersUserIdCommentsRoute
  '/_authenticated/users/$userId/likes': typeof AuthenticatedUsersUserIdLikesRoute
  '/_authenticated/users/$userId_/followers': typeof AuthenticatedUsersUserIdFollowersRoute
  '/_authenticated/users/$userId_/followings': typeof AuthenticatedUsersUserIdFollowingsRoute
  '/_authenticated/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/edit-profile'
    | '/follow-requests'
    | '/follow-users'
    | '/home'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/$postId/likes'
    | '/users/$userId/comments'
    | '/users/$userId/likes'
    | '/users/$userId/followers'
    | '/users/$userId/followings'
    | '/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/edit-profile'
    | '/follow-requests'
    | '/follow-users'
    | '/home'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/posts/$postId'
    | '/posts/$postId/likes'
    | '/users/$userId/comments'
    | '/users/$userId/likes'
    | '/users/$userId/followers'
    | '/users/$userId/followings'
    | '/users/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/about'
    | '/_authenticated/edit-profile'
    | '/_authenticated/follow-requests'
    | '/_authenticated/follow-users'
    | '/_authenticated/home'
    | '/_authenticated/settings'
    | '/_guest/signin'
    | '/_guest/signup'
    | '/_authenticated/'
    | '/_authenticated/posts/$postId'
    | '/_authenticated/users/$userId'
    | '/_authenticated/posts/$postId_/likes'
    | '/_authenticated/users/$userId/comments'
    | '/_authenticated/users/$userId/likes'
    | '/_authenticated/users/$userId_/followers'
    | '/_authenticated/users/$userId_/followings'
    | '/_authenticated/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edit-profile': {
      id: '/_authenticated/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthenticatedEditProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/follow-requests': {
      id: '/_authenticated/follow-requests'
      path: '/follow-requests'
      fullPath: '/follow-requests'
      preLoaderRoute: typeof AuthenticatedFollowRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/follow-users': {
      id: '/_authenticated/follow-users'
      path: '/follow-users'
      fullPath: '/follow-users'
      preLoaderRoute: typeof AuthenticatedFollowUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_guest/signin': {
      id: '/_guest/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof GuestSigninRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/posts/$postId': {
      id: '/_authenticated/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthenticatedPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts/$postId_/likes': {
      id: '/_authenticated/posts/$postId_/likes'
      path: '/posts/$postId/likes'
      fullPath: '/posts/$postId/likes'
      preLoaderRoute: typeof AuthenticatedPostsPostIdLikesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId/': {
      id: '/_authenticated/users/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof AuthenticatedUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedUsersUserIdRoute
    }
    '/_authenticated/users/$userId/comments': {
      id: '/_authenticated/users/$userId/comments'
      path: '/comments'
      fullPath: '/users/$userId/comments'
      preLoaderRoute: typeof AuthenticatedUsersUserIdCommentsRouteImport
      parentRoute: typeof AuthenticatedUsersUserIdRoute
    }
    '/_authenticated/users/$userId/likes': {
      id: '/_authenticated/users/$userId/likes'
      path: '/likes'
      fullPath: '/users/$userId/likes'
      preLoaderRoute: typeof AuthenticatedUsersUserIdLikesRouteImport
      parentRoute: typeof AuthenticatedUsersUserIdRoute
    }
    '/_authenticated/users/$userId_/followers': {
      id: '/_authenticated/users/$userId_/followers'
      path: '/users/$userId/followers'
      fullPath: '/users/$userId/followers'
      preLoaderRoute: typeof AuthenticatedUsersUserIdFollowersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId_/followings': {
      id: '/_authenticated/users/$userId_/followings'
      path: '/users/$userId/followings'
      fullPath: '/users/$userId/followings'
      preLoaderRoute: typeof AuthenticatedUsersUserIdFollowingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedUsersUserIdRouteChildren {
  AuthenticatedUsersUserIdCommentsRoute: typeof AuthenticatedUsersUserIdCommentsRoute
  AuthenticatedUsersUserIdLikesRoute: typeof AuthenticatedUsersUserIdLikesRoute
  AuthenticatedUsersUserIdIndexRoute: typeof AuthenticatedUsersUserIdIndexRoute
}

const AuthenticatedUsersUserIdRouteChildren: AuthenticatedUsersUserIdRouteChildren =
  {
    AuthenticatedUsersUserIdCommentsRoute:
      AuthenticatedUsersUserIdCommentsRoute,
    AuthenticatedUsersUserIdLikesRoute: AuthenticatedUsersUserIdLikesRoute,
    AuthenticatedUsersUserIdIndexRoute: AuthenticatedUsersUserIdIndexRoute,
  }

const AuthenticatedUsersUserIdRouteWithChildren =
  AuthenticatedUsersUserIdRoute._addFileChildren(
    AuthenticatedUsersUserIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedEditProfileRoute: typeof AuthenticatedEditProfileRoute
  AuthenticatedFollowRequestsRoute: typeof AuthenticatedFollowRequestsRoute
  AuthenticatedFollowUsersRoute: typeof AuthenticatedFollowUsersRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPostsPostIdRoute: typeof AuthenticatedPostsPostIdRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRouteWithChildren
  AuthenticatedPostsPostIdLikesRoute: typeof AuthenticatedPostsPostIdLikesRoute
  AuthenticatedUsersUserIdFollowersRoute: typeof AuthenticatedUsersUserIdFollowersRoute
  AuthenticatedUsersUserIdFollowingsRoute: typeof AuthenticatedUsersUserIdFollowingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedEditProfileRoute: AuthenticatedEditProfileRoute,
  AuthenticatedFollowRequestsRoute: AuthenticatedFollowRequestsRoute,
  AuthenticatedFollowUsersRoute: AuthenticatedFollowUsersRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPostsPostIdRoute: AuthenticatedPostsPostIdRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRouteWithChildren,
  AuthenticatedPostsPostIdLikesRoute: AuthenticatedPostsPostIdLikesRoute,
  AuthenticatedUsersUserIdFollowersRoute:
    AuthenticatedUsersUserIdFollowersRoute,
  AuthenticatedUsersUserIdFollowingsRoute:
    AuthenticatedUsersUserIdFollowingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestSigninRoute: typeof GuestSigninRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestSigninRoute: GuestSigninRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
