/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LoginCallbackRouteImport } from './routes/login_.callback'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFollowUsersRouteImport } from './routes/_authenticated/follow-users'
import { Route as AuthenticatedFollowRequestsRouteImport } from './routes/_authenticated/follow-requests'
import { Route as AuthenticatedEditProfileRouteImport } from './routes/_authenticated/edit-profile'
import { Route as AuthenticatedCreatePostRouteImport } from './routes/_authenticated/create-post'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users.$userId'
import { Route as AuthenticatedPostsPostIdRouteImport } from './routes/_authenticated/posts.$postId'
import { Route as AuthenticatedUsersUserIdFollowingsRouteImport } from './routes/_authenticated/users.$userId_.followings'
import { Route as AuthenticatedUsersUserIdFollowersRouteImport } from './routes/_authenticated/users.$userId_.followers'
import { Route as AuthenticatedPostsPostIdLikesRouteImport } from './routes/_authenticated/posts.$postId_.likes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login_/callback',
  path: '/login/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFollowUsersRoute =
  AuthenticatedFollowUsersRouteImport.update({
    id: '/follow-users',
    path: '/follow-users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFollowRequestsRoute =
  AuthenticatedFollowRequestsRouteImport.update({
    id: '/follow-requests',
    path: '/follow-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEditProfileRoute =
  AuthenticatedEditProfileRouteImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreatePostRoute = AuthenticatedCreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPostsPostIdRoute =
  AuthenticatedPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdFollowingsRoute =
  AuthenticatedUsersUserIdFollowingsRouteImport.update({
    id: '/users/$userId_/followings',
    path: '/users/$userId/followings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdFollowersRoute =
  AuthenticatedUsersUserIdFollowersRouteImport.update({
    id: '/users/$userId_/followers',
    path: '/users/$userId/followers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPostsPostIdLikesRoute =
  AuthenticatedPostsPostIdLikesRouteImport.update({
    id: '/posts/$postId_/likes',
    path: '/posts/$postId/likes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AuthenticatedAboutRoute
  '/create-post': typeof AuthenticatedCreatePostRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/follow-requests': typeof AuthenticatedFollowRequestsRoute
  '/follow-users': typeof AuthenticatedFollowUsersRoute
  '/home': typeof AuthenticatedHomeRoute
  '/login/callback': typeof LoginCallbackRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/posts/$postId/likes': typeof AuthenticatedPostsPostIdLikesRoute
  '/users/$userId/followers': typeof AuthenticatedUsersUserIdFollowersRoute
  '/users/$userId/followings': typeof AuthenticatedUsersUserIdFollowingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AuthenticatedAboutRoute
  '/create-post': typeof AuthenticatedCreatePostRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/follow-requests': typeof AuthenticatedFollowRequestsRoute
  '/follow-users': typeof AuthenticatedFollowUsersRoute
  '/home': typeof AuthenticatedHomeRoute
  '/login/callback': typeof LoginCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/posts/$postId/likes': typeof AuthenticatedPostsPostIdLikesRoute
  '/users/$userId/followers': typeof AuthenticatedUsersUserIdFollowersRoute
  '/users/$userId/followings': typeof AuthenticatedUsersUserIdFollowingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/create-post': typeof AuthenticatedCreatePostRoute
  '/_authenticated/edit-profile': typeof AuthenticatedEditProfileRoute
  '/_authenticated/follow-requests': typeof AuthenticatedFollowRequestsRoute
  '/_authenticated/follow-users': typeof AuthenticatedFollowUsersRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/login_/callback': typeof LoginCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/posts/$postId': typeof AuthenticatedPostsPostIdRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/posts/$postId_/likes': typeof AuthenticatedPostsPostIdLikesRoute
  '/_authenticated/users/$userId_/followers': typeof AuthenticatedUsersUserIdFollowersRoute
  '/_authenticated/users/$userId_/followings': typeof AuthenticatedUsersUserIdFollowingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/create-post'
    | '/edit-profile'
    | '/follow-requests'
    | '/follow-users'
    | '/home'
    | '/login/callback'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/$postId/likes'
    | '/users/$userId/followers'
    | '/users/$userId/followings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/create-post'
    | '/edit-profile'
    | '/follow-requests'
    | '/follow-users'
    | '/home'
    | '/login/callback'
    | '/'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/$postId/likes'
    | '/users/$userId/followers'
    | '/users/$userId/followings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/about'
    | '/_authenticated/create-post'
    | '/_authenticated/edit-profile'
    | '/_authenticated/follow-requests'
    | '/_authenticated/follow-users'
    | '/_authenticated/home'
    | '/login_/callback'
    | '/_authenticated/'
    | '/_authenticated/posts/$postId'
    | '/_authenticated/users/$userId'
    | '/_authenticated/posts/$postId_/likes'
    | '/_authenticated/users/$userId_/followers'
    | '/_authenticated/users/$userId_/followings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login_/callback': {
      id: '/login_/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/follow-users': {
      id: '/_authenticated/follow-users'
      path: '/follow-users'
      fullPath: '/follow-users'
      preLoaderRoute: typeof AuthenticatedFollowUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/follow-requests': {
      id: '/_authenticated/follow-requests'
      path: '/follow-requests'
      fullPath: '/follow-requests'
      preLoaderRoute: typeof AuthenticatedFollowRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edit-profile': {
      id: '/_authenticated/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthenticatedEditProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-post': {
      id: '/_authenticated/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof AuthenticatedCreatePostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts/$postId': {
      id: '/_authenticated/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthenticatedPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId_/followings': {
      id: '/_authenticated/users/$userId_/followings'
      path: '/users/$userId/followings'
      fullPath: '/users/$userId/followings'
      preLoaderRoute: typeof AuthenticatedUsersUserIdFollowingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId_/followers': {
      id: '/_authenticated/users/$userId_/followers'
      path: '/users/$userId/followers'
      fullPath: '/users/$userId/followers'
      preLoaderRoute: typeof AuthenticatedUsersUserIdFollowersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts/$postId_/likes': {
      id: '/_authenticated/posts/$postId_/likes'
      path: '/posts/$postId/likes'
      fullPath: '/posts/$postId/likes'
      preLoaderRoute: typeof AuthenticatedPostsPostIdLikesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedCreatePostRoute: typeof AuthenticatedCreatePostRoute
  AuthenticatedEditProfileRoute: typeof AuthenticatedEditProfileRoute
  AuthenticatedFollowRequestsRoute: typeof AuthenticatedFollowRequestsRoute
  AuthenticatedFollowUsersRoute: typeof AuthenticatedFollowUsersRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPostsPostIdRoute: typeof AuthenticatedPostsPostIdRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedPostsPostIdLikesRoute: typeof AuthenticatedPostsPostIdLikesRoute
  AuthenticatedUsersUserIdFollowersRoute: typeof AuthenticatedUsersUserIdFollowersRoute
  AuthenticatedUsersUserIdFollowingsRoute: typeof AuthenticatedUsersUserIdFollowingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedCreatePostRoute: AuthenticatedCreatePostRoute,
  AuthenticatedEditProfileRoute: AuthenticatedEditProfileRoute,
  AuthenticatedFollowRequestsRoute: AuthenticatedFollowRequestsRoute,
  AuthenticatedFollowUsersRoute: AuthenticatedFollowUsersRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPostsPostIdRoute: AuthenticatedPostsPostIdRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedPostsPostIdLikesRoute: AuthenticatedPostsPostIdLikesRoute,
  AuthenticatedUsersUserIdFollowersRoute:
    AuthenticatedUsersUserIdFollowersRoute,
  AuthenticatedUsersUserIdFollowingsRoute:
    AuthenticatedUsersUserIdFollowingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginCallbackRoute: LoginCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
